<?php

namespace Ly\HrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * experienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class experienceRepository extends EntityRepository
{

}
